steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/figure-service:latest
      - -f
      - Dockerfile.figure
      - .
images:
  - gcr.io/$PROJECT_ID/figure-service:latest
options:
  machineType: 'E2_HIGHCPU_8'
timeout: '1800s'
