"""
Extract flow-reactor engineering parameters for the C2 (remote-EWG) modeling substrates
from their source papers, via Gemini + Google Search grounding. Used to compute τ_mix
and Damköhler number Da = τ_mix·k_chem for chemical/mixing regime classification.

Only the 4 papers that contain the 12 C2 substrates are queried (Zhao: only the
corresponding-substrate literature). Unreported values -> null (no fabrication).

Run:  flowfigtabminer/bin/python extract_reactor_metadata.py
Needs a real GEMINI_API_KEY in ../../.env (24-char "your..." placeholder won't work).
"""
import os, json, re, time
from pathlib import Path
import pandas as pd
from google import genai
from google.genai import types

ROOT = Path(__file__).resolve().parents[2]   # FlowFigTabMiner/
BASE = Path(__file__).parent

def load_key():
    for line in (ROOT/".env").read_text().splitlines():
        if line.strip().startswith("GEMINI_API_KEY") and "=" in line:
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    return os.environ.get("GEMINI_API_KEY", "")

# 4 source papers of the 12 C2 substrates (paper_id, doi from clean dataset)
PAPERS = [
    dict(pid="AlkoxycarbonylFlow_2010_Nagaki", doi="10.1002/chem.201000876",
         title="A flow microreactor system enables organolithium reactions without protecting alkoxycarbonyl groups",
         substrates="methyl/ethyl/isopropyl/tert-butyl meta- and para-lithiobenzoate, generated by Br/Li exchange of the corresponding bromobenzoate with s-BuLi"),
    dict(pid="CyanoArLi_2010_Nagaki", doi="10.1039/b919325c",
         title="Generation and reactions of cyano-substituted aryllithiums using microflow/microreactor systems (Nagaki, Yoshida)",
         substrates="m- and p-cyanophenyllithium, generated by Br/Li exchange of bromobenzonitrile"),
    dict(pid="Homocoupling_2011_Nagaki", doi="10.3762/bjoc.7.122",
         title="Aryllithium homocoupling / functionalized aryllithium generation in flow microreactors (Nagaki, Yoshida)",
         substrates="functionalized aryllithium (incl. nitro-substituted) by Br/Li exchange"),
    dict(pid="NitroArLi_2009_Nagaki", doi="10.1002/anie.200904316",
         title="Generation of organolithiums bearing nitro groups using flow microreactors (Nagaki, Yoshida)",
         substrates="m-nitrophenyllithium and related nitro-aryllithium by Br/Li exchange"),
]

PROMPT = """You are extracting FLOW-REACTOR ENGINEERING parameters from ONE specific paper.

Paper DOI: {doi}
Title (approx): {title}
Target intermediates: {substrates}

From THIS paper only, find the microreactor setup used to GENERATE these aryllithium
intermediates by Br/Li (halogen-lithium) exchange. Return STRICT JSON (no prose):
{{
  "reactor_type": string|null,
  "micromixer_type": string|null,
  "mixer_inner_diameter_mm": number|null,
  "reactor_tube_inner_diameter_mm": number|null,
  "reactor_tube_length_cm": number|null,
  "flow_rate_total_mL_min": number|null,
  "flow_rate_per_stream_mL_min": array|null,
  "substrate_concentration_M": number|null,
  "base_reagent": string|null,
  "evidence_quote": string,
  "confidence": "high"|"medium"|"low"
}}

RULES:
- Use ONLY this exact paper (match the DOI). Do NOT borrow numbers from other papers.
- Convert all units to: mm, cm, mL/min, M.
- If a value is not reported in this paper, use null. Do NOT guess.
- evidence_quote: a short verbatim phrase (with page/section if possible) supporting the mixer/tube/flow numbers.
Return only the JSON object."""

def parse_json(txt):
    m = re.search(r"\{.*\}", txt, re.DOTALL)
    if not m: return {"_parse_error": txt[:300]}
    try: return json.loads(m.group(0))
    except Exception as e: return {"_parse_error": str(e), "_raw": m.group(0)[:400]}

def call_with_retry(client, model, contents, config, max_retries=6):
    """Exponential backoff for rate limits / server overload (429/503/RESOURCE_EXHAUSTED)."""
    for i in range(max_retries):
        try:
            return client.models.generate_content(model=model, contents=contents, config=config)
        except Exception as e:
            msg = str(e)
            transient = any(k in msg for k in
                ["429", "RESOURCE_EXHAUSTED", "503", "UNAVAILABLE", "500", "overload", "quota"]) \
                or "exhaust" in msg.lower()
            if transient and i < max_retries - 1:
                wait = (2 ** i) + 1  # 1,3,5,9,17,33s
                print(f"  服务器限流/拥堵，将在 {wait}s 后重试 ({i+1}/{max_retries})...", flush=True)
                time.sleep(wait)
            else:
                raise
    raise RuntimeError("达到最大重试次数，Gemini 服务器依然拥堵。")

def main():
    key = load_key()
    if key in ("", "gemini_api_key_here") or key.startswith("your"):
        raise SystemExit(f"GEMINI_API_KEY looks like a placeholder ({key[:6]}...). Set a real key in .env first.")
    client = genai.Client(api_key=key)
    cfg = types.GenerateContentConfig(
        tools=[types.Tool(google_search=types.GoogleSearch())], temperature=0.1)
    rows = []
    for p in PAPERS:
        print(f"[Gemini] {p['pid']} ({p['doi']}) ...", flush=True)
        try:
            r = call_with_retry(client, "gemini-2.5-flash", PROMPT.format(**p), cfg)
            d = parse_json(r.text)
        except Exception as e:
            d = {"_api_error": str(e)}
        d.update(paper_id=p["pid"], doi=p["doi"])
        rows.append(d)
        print("   ->", json.dumps({k: d.get(k) for k in
              ["reactor_type","mixer_inner_diameter_mm","reactor_tube_inner_diameter_mm",
               "reactor_tube_length_cm","flow_rate_total_mL_min","confidence"]}, ensure_ascii=False))
        time.sleep(5)
    df = pd.DataFrame(rows)
    out = BASE / "reactor_metadata_c2.csv"
    df.to_csv(out, index=False)
    print(f"\nSaved -> {out}")
    print(df.to_string())

if __name__ == "__main__":
    main()
